# Generated by Django 4.0.1 on 2023-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomMember',
            new_name='RoomDetails',
        ),
    ]
