# Generated by Django 4.0.1 on 2023-12-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_roommember_roomdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDetails',
            new_name='RoomMember',
        ),
    ]
