# Generated by Django 4.0.1 on 2024-01-19 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_alter_banner_id_alter_brand_id_alter_cartorder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('lang', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('feet', models.IntegerField(default=0)),
                ('inches', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('goal', models.CharField(blank=True, max_length=50)),
                ('training', models.CharField(blank=True, max_length=50)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('intrest', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
